### ISSUE TITLE
Segfault in computing graph xfers after PR #123

### ISSUE THREAD

**Issue by typerSniper** [quantum-compiler/quartz#124]
Hey, because of the recent PR #123, quartz segfaults while computing graph xfers from `Name_4_3_complete_ECC_set.json` (I suspect other ecc files would also segfault). I went through the debugger and found that the assertion `assert(node->index < (int)context->input_parameters.size());` on line 165 of tasograph.cpp, fails, and the next line segfaults. I was unable to determine how to fix that :/. I suspect that for creating new parameter nodes, you need to update the context somehow, but I am not sure.

**Comment by xumingkuan** [comment]
Is this fixed now?

**Comment by typerSniper** [comment]
Indeed
