### ISSUE TITLE
[qasm] Support multiple qregs

### ISSUE THREAD

**Issue by xumingkuan** [quantum-compiler/quartz#59]
Currently we only support one `qreg` statement, like
```qasm
OPENQASM 2.0;
include "qelib1.inc";
qreg q[40];
```

We may want to also support multiple `qreg` statements in some qasm files, like
```qasm
OPENQASM 2.0;
include "qelib1.inc";
qreg eval[39];
qreg q[1];
```

The implementation of this part is in `Graph::_from_qasm_stream`.

**Comment by zikun-li** [comment]
I agree with you that instead of implement it ourselves, we should look for a well-developed library.

**Comment by xumingkuan** [comment]
`qiskit.circuit.QuantumCircuit.from_qasm_file(...).data` returns a list of gates. I think we can translate this to a `CircuitSeq` object.

**Comment by xumingkuan** [comment]
Closing this issue for now. `CircuitSeq::from_qasm_file()` in #64 supports multiple qregs.
